name: flutter_timer_bloc
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1


  cupertino_icons: ^1.0.6

dev_dependencies:
  bloc_test: ^9.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  build_runner: ^2.4.9

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


